### PR TITLE
OHM-134: Added error checking for server and client

### PR DESCRIPTION
**Pull request by BMartinos**
This PR relates to issue: #460

### CODE REVIEW

**Comment by BMartinos** [comment]
Hey @devcritter @bausmeier @rcrichton ive added in some exception listens for the server but im not sure if ive maybe missed some types or places i need to still put it.

We also noticed a weird 'stop' process happening when the error occurs ( but not always ). This is explain a bit more in the issue #460

**Comment by rcrichton** [comment]
@BMartinos this looks good to me except can you use `logger.error` rather. Also, I wonder if this error is actually happening on the router (ie. outgoing connection) it may be looking for uncaught errors there to.

**Comment by devcritter** [comment]
Thanks @BMartinos looks good to me as well :+1: Agree that you should just switch to log.error.

**Comment by BMartinos** [comment]
Hey @rcrichton @devcritter ive updated the logger to use 'error'. also added an error listen in the router. If you can just review this for me again please. Thanks

**Comment by devcritter** [comment]
Sure, looks good to me :+1:

**Comment by rcrichton** [comment]
Thanks, looks good to me to :+1:

**Pull request merged**
