### PR TITLE
Authorise Channel Bug Fix

### PR DESCRIPTION
**Pull request by BMartinos**
This PR relates to issue: https://github.com/jembi/openhim-core-js/issues/443

### CODE REVIEW

**Comment by BMartinos** [comment]
Hey @devcritter Do you mind reviewing the PR for me when you get a chance. Thanks

**Comment by BMartinos** [comment]
Ive also made some changes in some of the comments. The apostrophe escaped the syntax highlighting in my IDE. Not sure if this is a common problem

**Comment by devcritter** [comment]
:+1: Thanks for picking this up @BMartinos 

My text editor doesn't have any issues with the apostrophes, but I see no issue in changing them.

**Comment by BMartinos** [comment]
closes #443

**Pull request merged**
