### PR TITLE
Fixes #579: upgraded mongoose and agenda

### LINKED ISSUE #579: Fix broken dependencies
The current master is breaking due to mongoose and agenda:

agenda ^0.6.0 gives
> /openhim-core-js/node_modules/mongoskin/lib/utils.js:33
  var skinClassName = 'Skin' + NativeClass.name;
                                          ^
TypeError: Cannot read property 'name' of undefined
    at makeSkinClass (/openhim-core-js/node_modules/mongoskin/lib/utils.js:33:43)
    at Object.<anonymous> (/openhim-core-js/node_modules/mongoskin/lib/admin.js:18:37)

Upgrading to ^0.7.0 breaks existing code however
> 2015-11-04T09:32:05.289Z - info: [worker1] Started rerun task processor
 /openhim-core-js/node_modules/agenda/lib/agenda.js:277
    this._collection.findAndModify({name: props.name, type: 'single'}, {}, update, {upsert: true, new: true}, processDbResult);
                    ^
 TypeError: Cannot read property 'findAndModify' of undefined
    at [object Object].Agenda.saveJob (/openhim-core-js/node_modules/agenda/lib/agenda.js:277:21)
    at Job.save (/openhim-core-js/node_modules/agenda/lib/job.js:217:15)
    at createJob (/openhim-core-js/node_modules/agenda/lib/agenda.js:192:9)
    at [object Object].Agenda.every (/openhim-core-js/node_modules/agenda/lib/agenda.js:182:12)
    at Object.setupAgenda (/openhim-core-js/src/alerts.coffee:283:10)
    at startAgenda (/openhim-core-js/src/server.coffee:232:12)
    at /openhim-core-js/src/server.coffee:525:21

mongoose 4.0.2 gives
> Error: Cannot find module 'mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/objectid'
    at Function.Module._resolveFilename (module.js:337:15)

though upgrading to 4.0.3 fixes the problem

### PR DESCRIPTION
**Pull request by devcritter**
Closes #579 

@rcrichton if you could please take a look?

### CODE REVIEW

**Comment by devcritter** [comment]
Not ready, the tests need fixing.

**Comment by devcritter** [comment]
Agenda now requires mongo 2.6 at a minimum

**Comment by devcritter** [comment]
if we're happy with that we'll have to update travis to use a newer version ([e.g.](https://www.theodo.fr/blog/2014/12/choose-a-specific-mongodb-version-in-travis/)).

**Comment by rcrichton** [comment]
Hey @devcritter, do we really need the latest agenda? Mongo 2.4.x is still the default that gets installed with the ubuntu 14.04 package. This would mean a more complex install process for new users. Also, I'd rather avoid `sudo: required` in travis as this reverts to using their old infrastructure which is slower to start builds.

**Comment by rcrichton** [comment]
Ahh, wait you just changed it. But still why the need for the latest agenda?

**Comment by devcritter** [comment]
Unfortunately the 0.6.x line is breaking now - it's a transitive mongoskin dep. I fully agree that it would be better to aim for the older mongo - but afraid it doesn't look like we have a choice.

Maybe you can try from your side too? Remove node_modules and see if master still works after npm install?

**Comment by rcrichton** [comment]
Cool, I'l give this a go and see what happens. Could we not revert to an earlier working version?

**Comment by devcritter** [comment]
Cool. I tried but didn't have any luck. (went back to 0.6.0)

**Pull request closed without merging**
