### PR TITLE
Report transactions list link

### LINKED ISSUE #593: Report emails link to an external OpenHIM logo, which is now broken

### LINKED ISSUE #594: Add link to transaction list from daily/weekly emails

### PR DESCRIPTION
**Pull request by rcrichton**
Closes #594 and closes #593 

@devcritter could you review this for me?

### CODE REVIEW

**Comment by devcritter** [comment]
@rcrichton looks good :+1: before merging though - mind picking up another quick change while you're busy with it anyway? The avg response times are coming through with as decimals with a lot of decimal places (e.g. 24.954954954954953). If their in ms I think we should even leave out the decimal part.

**Comment by rcrichton** [comment]
Hey @devcritter cool good idea. I'l have a quick look at that.

**Comment by rcrichton** [comment]
@devcritter please have another look. Added the rounding off of ave response time.

**Comment by devcritter** [comment]
Thanks for adding - looks good :+1:

**Pull request merged**
